version: "3.8"
services:
    detection:
        privileged: True
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            - DISPLAY=10.0.0.10:0.0
        build:
            context: .
            dockerfile: detection.Dockerfile
        image: sdp-detection
        volumes:
            - ./src:/app
            - ./input:/input
    webserver:
        build:
            context: .
            dockerfile: webserver.Dockerfile
        image: sdp-webserver
        volumes:
            - ./webserver:/app
        ports:
            - "80:3000"