version: "3.8"
services:
    detection:
        build:
            context: .
            dockerfile: detection.Dockerfile
        image: sdp-detection
        volumes:
            - ./src:/app
            - ./input:/input
    webserver:
        build:
            context: .
            dockerfile: webserver.Dockerfile
        image: sdp-webserver
        volumes:
            - ./webserver:/app
        ports:
            - "80:3000"